# Workflow for running tests on Linux
name: Test Linux

on: [push]

jobs:
  # Build job
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install Swift
        uses: sersoft-gmbh/swifty-linux-action@v3
        with:
            branch-name: swift-6.0-branch
            version-tag: swift-6.0-DEVELOPMENT-SNAPSHOT-2024-06-12-a
            # release-version: 6.0
      - name: Build
        run: swift build
      - name: Test
        run: swift test
